import { Badge, Button, Card, OverlayTrigger, Popover } from '@govtechsg/sgds-react';
import type { Finding, FindingSeverity } from '@/types';

function FindingsInfoPopover() {
  const popover = (
    <Popover id="info-findings" style={{ maxWidth: '360px' }}>
      <Popover.Header>Deterministic Findings — How it works</Popover.Header>
      <Popover.Body className="small">
        <p className="mb-2">
          These findings are computed deterministically from the full dataset — not generated by the
          LLM. They are the input that drives the narrative.
        </p>
        <p className="mb-2">
          Eight detectors run over every conversation before the LLM is invoked:{' '}
          <strong>nDPI risk flags</strong>, <strong>beacon/C2 patterns</strong>,{' '}
          <strong>TLS anomalies</strong>, <strong>volume anomalies</strong>,{' '}
          <strong>fan-out/scanning</strong>, <strong>long sessions</strong>,{' '}
          <strong>unknown application traffic</strong>, and{' '}
          <strong>port-protocol mismatches</strong>.
        </p>
        <p className="mb-0">
          The LLM only writes prose from these findings — it cannot invent findings not listed here.
        </p>
      </Popover.Body>
    </Popover>
  );
  return (
    <OverlayTrigger trigger="click" placement="left" overlay={popover} rootClose>
      <Button
        type="button"
        variant="link"
        className="p-0 text-muted ms-1"
        style={{ lineHeight: 1 }}
        aria-label="About Deterministic Findings"
      >
        <i className="bi bi-info-circle" style={{ fontSize: '0.9rem' }}></i>
      </Button>
    </OverlayTrigger>
  );
}

const SEVERITY_ORDER: FindingSeverity[] = ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW'];

function severityBadgeBg(severity: FindingSeverity): string {
  switch (severity) {
    case 'CRITICAL': return 'danger';
    case 'HIGH': return 'warning';
    case 'MEDIUM': return 'info';
    case 'LOW': return 'secondary';
  }
}

function severityBadgeText(severity: FindingSeverity): 'dark' | undefined {
  switch (severity) {
    case 'HIGH':
    case 'MEDIUM': return 'dark';
    default: return undefined;
  }
}

function severityHeaderClass(severity: FindingSeverity): string {
  switch (severity) {
    case 'CRITICAL':
      return 'text-danger';
    case 'HIGH':
      return 'text-warning';
    case 'MEDIUM':
      return 'text-info';
    case 'LOW':
      return 'text-secondary';
  }
}

interface FindingCardProps {
  finding: Finding;
}

function FindingCard({ finding }: FindingCardProps) {
  const metricEntries = finding.metrics
    ? Object.entries(finding.metrics).filter(([, v]) => v !== null)
    : [];

  return (
    <Card className="mb-2">
      <Card.Body className="py-2 px-3">
        <div className="d-flex align-items-start gap-2 mb-1">
          <Badge
            bg={severityBadgeBg(finding.severity)}
            text={severityBadgeText(finding.severity)}
            style={{ whiteSpace: 'nowrap', fontSize: '0.7rem' }}
          >
            {finding.severity}
          </Badge>
          <h6 className="mb-0 small fw-semibold" style={{ lineHeight: '1.4' }}>
            {finding.title}
          </h6>
        </div>
        <p className="mb-1 small text-muted" style={{ lineHeight: '1.4' }}>
          {finding.summary}
        </p>
        {metricEntries.length > 0 && (
          <div className="d-flex flex-wrap gap-2 mb-1">
            {metricEntries.map(([key, value]) => (
              <span
                key={key}
                className="text-muted"
                style={{ fontSize: '0.72rem', fontFamily: 'monospace' }}
              >
                {key}: <strong>{String(value)}</strong>
              </span>
            ))}
          </div>
        )}
        {finding.affectedIps && finding.affectedIps.length > 0 && (
          <div className="d-flex flex-wrap gap-1">
            {finding.affectedIps.map(ip => (
              <Badge
                key={ip}
                bg="light"
                text="dark"
                className="border"
                style={{ fontSize: '0.7rem', fontFamily: 'monospace' }}
              >
                {ip}
              </Badge>
            ))}
          </div>
        )}
      </Card.Body>
    </Card>
  );
}

interface Props {
  findings: Finding[];
}

export function FindingsPanel({ findings }: Props) {
  const grouped = SEVERITY_ORDER.reduce<Record<FindingSeverity, Finding[]>>(
    (acc, sev) => {
      acc[sev] = findings.filter(f => f.severity === sev);
      return acc;
    },
    { CRITICAL: [], HIGH: [], MEDIUM: [], LOW: [] }
  );

  const total = findings.length;
  const criticalCount = grouped.CRITICAL.length;
  const highCount = grouped.HIGH.length;

  return (
    <Card>
      <Card.Header className="d-flex align-items-center justify-content-between">
        <div className="d-flex align-items-center gap-2">
          <h6 className="mb-0">
            <i className="bi bi-shield-exclamation me-2"></i>
            Deterministic Findings
          </h6>
          <FindingsInfoPopover />
        </div>
        <div className="d-flex gap-2 align-items-center">
          <span className="text-muted small">
            {total} finding{total !== 1 ? 's' : ''}
          </span>
          {criticalCount > 0 && <Badge bg="danger">{criticalCount} CRITICAL</Badge>}
          {highCount > 0 && <Badge bg="warning" text="dark">{highCount} HIGH</Badge>}
        </div>
      </Card.Header>
      <Card.Body>
        {SEVERITY_ORDER.map(sev => {
          const group = grouped[sev];
          if (group.length === 0) return null;
          return (
            <div key={sev} className="mb-3">
              <h6 className={`small fw-bold text-uppercase mb-2 ${severityHeaderClass(sev)}`}>
                {sev} ({group.length})
              </h6>
              {group.map((finding, i) => (
                <FindingCard key={`${sev}-${i}`} finding={finding} />
              ))}
            </div>
          );
        })}
      </Card.Body>
    </Card>
  );
}
