import { OverlayTrigger, Popover } from '@govtechsg/sgds-react';
import type { Highlight } from '@/types';
import { formatTimestamp } from '@/utils/formatters';

function InfoPopover() {
  const popover = (
    <Popover id="info-key-highlights" style={{ maxWidth: '320px' }}>
      <Popover.Header>Key Highlights — How it works</Popover.Header>
      <Popover.Body className="small">
        <p className="mb-2">
          Generated by the LLM using: a <strong>Security Risk Clusters</strong> section covering
          every risk type detected across the full dataset, diversity-selected example conversations
          (one per risk type), and pre-computed aggregates (ASNs, protocol risk, TLS anomalies,
          beacon candidates).
        </p>
        <p className="mb-2">
          <strong>Limitations:</strong>
        </p>
        <ul className="mb-0 ps-3">
          <li>
            Every risk <em>type</em> in the capture is represented, but individual low-volume
            conversations outside the example slots are not shown to the LLM directly.
          </li>
          <li>
            Highlights reflect the LLM's interpretation — benign activity can occasionally be
            misclassified.
          </li>
          <li>Timestamps are extracted from the LLM response and may be approximate.</li>
        </ul>
      </Popover.Body>
    </Popover>
  );
  return (
    <OverlayTrigger trigger="click" placement="right" overlay={popover} rootClose>
      <button
        type="button"
        className="btn btn-link p-0 text-muted ms-2"
        style={{ lineHeight: 1 }}
        aria-label="About Key Highlights"
      >
        <i className="bi bi-info-circle" style={{ fontSize: '0.9rem' }}></i>
      </button>
    </OverlayTrigger>
  );
}

interface AnomalyHighlightProps {
  highlights: Highlight[];
}

export const AnomalyHighlight = ({ highlights }: AnomalyHighlightProps) => {
  const getHighlightClass = (type: string) => {
    const classes: Record<string, string> = {
      anomaly: 'alert-danger',
      warning: 'alert-warning',
      insight: 'alert-info',
      info: 'alert-primary',
    };
    return classes[type] || 'alert-secondary';
  };

  const getHighlightIcon = (type: string) => {
    const icons: Record<string, string> = {
      anomaly: 'bi-shield-exclamation',
      warning: 'bi-exclamation-triangle',
      insight: 'bi-lightbulb',
      info: 'bi-info-circle',
    };
    return icons[type] || 'bi-circle';
  };

  const sortedHighlights = [...highlights].sort((a, b) => {
    // Sort by severity: anomaly > warning > insight > info
    const severityOrder: Record<string, number> = {
      anomaly: 0,
      warning: 1,
      insight: 2,
      info: 3,
    };
    return (severityOrder[a.type] || 4) - (severityOrder[b.type] || 4);
  });

  return (
    <div className="anomaly-highlight">
      <h5 className="mb-3 d-flex align-items-center">
        Key Highlights
        <InfoPopover />
      </h5>

      {sortedHighlights.map(highlight => (
        <div
          key={highlight.id}
          className={`alert ${getHighlightClass(highlight.type)} d-flex`}
          role="alert"
        >
          <div className="flex-shrink-0 me-3">
            <i className={`bi ${getHighlightIcon(highlight.type)} fs-4`}></i>
          </div>
          <div className="flex-grow-1">
            <h6 className="alert-heading mb-1">{highlight.title}</h6>
            <p className="mb-1">{highlight.description}</p>
            {highlight.timestamp && (
              <small className="text-muted">
                <i className="bi bi-clock me-1"></i>
                {formatTimestamp(highlight.timestamp)}
              </small>
            )}
          </div>
        </div>
      ))}

      {highlights.length === 0 && (
        <div className="alert alert-secondary">
          <p className="mb-0">No highlights to display</p>
        </div>
      )}
    </div>
  );
};
